#+STARTUP: noindent showeverything
#+OPTIONS: toc:nil; html-postamble:nil
#+BEGIN_HTML
---
layout: page
title: Docker
date: 2016-08-16
category: trouble
permalink: trouble/docker
---
#+END_HTML


* Accessing the Container 

Here's a rundown of ~access_lab.sh~.

#+BEGIN_SRC sh
#!/bin/bash

docker run -it -p 127.0.0.1:8015:8000 \
       --user="$(id -u):$(id -g)" \
       -v $(pwd):/home/lab \
       felix11h/aniso_netw_env \
       /bin/bash -c \
       'source /home/docker/env/neurosci/bin/activate;
        screen -d -m /home/docker/env/neurosci/bin/smtweb --allips;
        source startup_messg.sh;
        bash'
#+END_SRC

Here
#+BEGIN_SRC sh
docker run -it
#+END_SRC
runs a docker image (specified as ~felix11h/aniso_netw_env~ a few lines below) in an interactive container. 

The following options and additional inputs are used:

The argument
#+BEGIN_SRC sh
-p 127.0.0.1:8015:8000
#+END_SRC
publishes ~0.0.0.0:8000~ of the container to ~127.0.0.1:8015~ of the Docker host.

With 
#+BEGIN_SRC sh
-user="$(id -u):$(id -g)" 
#+END_SRC
the current user is specified as the Docker user, this helps prevent any permissions problems on the files created from simulations within the container.

The option
#+BEGIN_SRC sh
-v $(pwd):/home/lab 
#+END_SRC
maps the current directory to ~/home/lab~ within the container as a shared volume.

The next line
#+BEGIN_SRC sh
felix11h/aniso_netw_env 
#+END_SRC
is the name of the Docker image used as it is available on [[https://hub.docker.com/r/felix11h/aniso_netw_env/][Docker Hub]].

The last line of commands
#+BEGIN_SRC sh
/bin/bash -c \
 'source /home/docker/env/neurosci/bin/activate;
  screen -d -m /home/docker/env/neurosci/bin/smtweb --allips;
  source startup_messg.sh;
  bash'
#+END_SRC

are a set of shell commands that are executed at startup of the container. 

First
#+BEGIN_SRC sh
source /home/docker/env/neurosci/bin/activate
#+END_SRC
activates a [[https://virtualenv.pypa.io/en/stable/][virtualenv]] in which Sumatra is installed, then with

#+BEGIN_SRC sh
screen -d -m /home/docker/env/neurosci/bin/smtweb --allips
#+END_SRC

the window manager [[https://www.gnu.org/software/screen/][screen]] is used to run the process ~smtweb --allips~ in a detached session (~-d~) in the background. The flag ~allips~ is necessary to run the Sumatra web interface at ~0.0.0.0:8000~, as opposed to ~127.0.0.1:8000~, which Docker assumes when forwarding publishing ports to the host.

Finally, 
#+BEGIN_SRC sh
source startup_messg.sh
#+END_SRC
displays the startup message and with the last command
#+BEGIN_SRC sh
bash
#+END_SRC
a bash terminal is provided to the user.
