#+STARTUP: noindent showeverything
#+OPTIONS: toc:nil; html-postamble:nil
#+BEGIN_HTML
---
layout: page
title: Docker
date: 2016-08-16
category: reproduce
permalink: reproduce/docker
---
#+END_HTML

I provide the full environment used for all computations referenced in the article in form of Docker image. In short, [[https://www.docker.com/][Docker]] uses virtualization on the operating system level to provide "containers" for Linux applications and has been --Boettinger

* Docker image

The Docker image used for this project is ~felix11h/aniso_netw_env~ and is available on [[https://hub.docker.com/r/felix11h/aniso_netw_env/][Docker Hub]]. A short list of the most important dependencies included in this image are 

 - Python
 - scipy
 - Graph Tool
 - tex-live
 - [[http://neuralensemble.org/sumatra/][Sumatra]] 0.7

* Accessing the Docker container

The computational environment can be most easily accessed using the provided bash script ~access_lab.sh~. In the directory,
#+BEGIN_SRC sh
source access_lab.sh
#+END_SRC
to start the container. The image ~felix11h/aniso_netw_env~ will be downloaded automatically if it's not available on your machine already (this will take some time and around 5 GB of disk space!). 

In your terminal you should now see something along the lines of

#+BEGIN_SRC sh
docker@c30441c7f888:/home/lab$
#+END_SRC

indicating that you've successfully started the container and have now access to all of the tools listed above. You can now access the lab notebook through the [[http://anisotropic-connectivity-local-circuits.github.io/reproduce/sumatra][Sumatra]] web interface. 

 
